name: fastio
description: A simple but powerful HTTP Client for Dart inspired by OkHttp.
version: 0.0.1
# author: v7lin <v7lin@qq.com>
homepage: https://github.com/rxreader/fastio

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  test:

  pedantic:
