name: fastio_cache
description: HTTP Cache (RFC 7234) support for fastio using LRU replacement strategy.
version: 0.0.1
# author: v7lin <v7lin@qq.com>
homepage: https://github.com/rxreader/fastio

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  test:

  pedantic:
